version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: todo-database
      POSTGRES_PASSWORD: todo-database
      POSTGRES_DB: todo-database
    ports:
      - 5432:5432

